# Generated by Django 4.2.1 on 2023-05-16 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import member.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Pays')),
                ('profile_picture', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=member.models.photo_directory_path, verbose_name='Photo de profil')),
                ('current_species', models.TextField(blank=True, help_text='Une espèce par ligne', null=True, verbose_name='Vos espèces actuelles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
