# Generated by Django 4.2.1 on 2023-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproductionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Période de reproduction',
                'verbose_name_plural': 'Périodes de reproduction',
            },
        ),
        migrations.AddField(
            model_name='amphibian',
            name='reproduction',
            field=models.CharField(blank=True, choices=[('O', 'Ovipare'), ('V', 'Vivipare'), ('I', 'Ovovivipare')], default='0', max_length=1, verbose_name='Mode de reproduction'),
        ),
        migrations.AddField(
            model_name='arthropod',
            name='reproduction',
            field=models.CharField(blank=True, choices=[('O', 'Ovipare'), ('V', 'Vivipare'), ('I', 'Ovovivipare')], default='0', max_length=1, verbose_name='Mode de reproduction'),
        ),
        migrations.AddField(
            model_name='lizard',
            name='reproduction',
            field=models.CharField(blank=True, choices=[('O', 'Ovipare'), ('V', 'Vivipare'), ('I', 'Ovovivipare')], default='0', max_length=1, verbose_name='Mode de reproduction'),
        ),
        migrations.AddField(
            model_name='snake',
            name='dentition',
            field=models.CharField(choices=[('A', 'Aglyphe'), ('O', 'Opistoglyphe'), ('T', 'Opisthodonte'), ('P', 'Protégroglyphe'), ('S', 'Solénoglyphe')], default='A', max_length=1, verbose_name='Dentition'),
        ),
        migrations.AddField(
            model_name='snake',
            name='reproduction',
            field=models.CharField(blank=True, choices=[('O', 'Ovipare'), ('V', 'Vivipare'), ('I', 'Ovovivipare')], default='0', max_length=1, verbose_name='Mode de reproduction'),
        ),
        migrations.AddField(
            model_name='turtle',
            name='reproduction',
            field=models.CharField(blank=True, choices=[('O', 'Ovipare'), ('V', 'Vivipare'), ('I', 'Ovovivipare')], default='0', max_length=1, verbose_name='Mode de reproduction'),
        ),
        migrations.AddField(
            model_name='amphibian',
            name='reproduction_period',
            field=models.ManyToManyField(blank=True, to='card.reproductionperiod'),
        ),
        migrations.AddField(
            model_name='arthropod',
            name='reproduction_period',
            field=models.ManyToManyField(blank=True, to='card.reproductionperiod'),
        ),
        migrations.AddField(
            model_name='lizard',
            name='reproduction_period',
            field=models.ManyToManyField(blank=True, to='card.reproductionperiod'),
        ),
        migrations.AddField(
            model_name='snake',
            name='reproduction_period',
            field=models.ManyToManyField(blank=True, to='card.reproductionperiod'),
        ),
        migrations.AddField(
            model_name='turtle',
            name='reproduction_period',
            field=models.ManyToManyField(blank=True, to='card.reproductionperiod'),
        ),
    ]
