# Generated by Django 4.2.1 on 2023-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_reproductionperiod_amphibian_reproduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amphibian',
            name='main_mores',
            field=models.CharField(choices=[('F', 'Fouisseur'), ('T', 'Terrestre'), ('A', 'Arboricole')], max_length=1, verbose_name='Moeurs principale'),
        ),
        migrations.AlterField(
            model_name='arthropod',
            name='main_mores',
            field=models.CharField(choices=[('F', 'Fouisseur'), ('T', 'Terrestre'), ('A', 'Arboricole')], max_length=1, verbose_name='Moeurs principale'),
        ),
        migrations.AlterField(
            model_name='lizard',
            name='main_mores',
            field=models.CharField(choices=[('F', 'Fouisseur'), ('T', 'Terrestre'), ('A', 'Arboricole')], max_length=1, verbose_name='Moeurs principale'),
        ),
        migrations.AlterField(
            model_name='snake',
            name='main_mores',
            field=models.CharField(choices=[('F', 'Fouisseur'), ('T', 'Terrestre'), ('A', 'Arboricole')], max_length=1, verbose_name='Moeurs principale'),
        ),
        migrations.AlterField(
            model_name='turtle',
            name='main_mores',
            field=models.CharField(choices=[('F', 'Fouisseur'), ('T', 'Terrestre'), ('A', 'Arboricole')], max_length=1, verbose_name='Moeurs principale'),
        ),
    ]
