# Generated by Django 4.2.1 on 2023-05-16 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documentation.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now=True)),
                ('category', models.CharField(choices=[('A', 'Amphibiens'), ('R', 'Arthropodes'), ('L', 'Lézards'), ('S', 'Serpents'), ('T', 'Tortues')], max_length=1)),
                ('title', models.CharField(help_text='Choisissez un titre pertinent', max_length=256, verbose_name='Title')),
                ('banner', sorl.thumbnail.fields.ImageField(help_text='Choisissez une image pertinente', upload_to=documentation.models.documentation_directory_path)),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('last_update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_modifier', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documentation',
                'verbose_name_plural': 'Documentations',
            },
        ),
    ]
